export const spotlightData = [
  {
    title: 'Hotel-California-Odissi',
    player: 'youtube',
    url: 'Fhp1pVrqOlE',
    start: 4,
    thumbnail: 'https://img.youtube.com/vi/Fhp1pVrqOlE/maxresdefault.jpg',
  },
  {
    title: 'Prema-Prema',
    player: 'youtube',
    url: 'fplAPb4FEx0',
    start: 0,
    thumbnail: 'https://img.youtube.com/vi/fplAPb4FEx0/maxresdefault.jpg',
  },
  {
    title: 'Albela-Sajan-HipHop',
    player: 'youtube',
    url: 'zGYPqQDf9Iw',
    start: 4,
    thumbnail: 'https://img.youtube.com/vi/zGYPqQDf9Iw/maxresdefault.jpg',
  },
  {
    title: 'Kathak-Senorita-Despacito',
    player: 'youtube',
    url: 'G_nSq-cVdGU',
    start: 4,
    thumbnail: 'https://img.youtube.com/vi/G_nSq-cVdGU/maxresdefault.jpg',
  },
  {
    title: 'Swarabindu',
    player: 'youtube',
    url: 'ECuFmeDuo9k',
    start: 0,
    thumbnail: 'https://img.youtube.com/vi/ECuFmeDuo9k/maxresdefault.jpg',
  },
  {
    title: 'Thillana-2',
    player: 'youtube',
    url: 'XjouopoWpTQ',
    start: 0,
    thumbnail: 'https://img.youtube.com/vi/XjouopoWpTQ/hqdefault.jpg',
  },
  {
    title: 'Nayantara-tribute',
    player: 'youtube',
    url: 'vFPyrjz-uZo',
    start: 0,
    thumbnail: 'https://img.youtube.com/vi/vFPyrjz-uZo/maxresdefault.jpg',
  },
  {
    title: 'Ek-do-teen',
    player: 'youtube',
    url: '6HLIFMyJxWA',
    start: 0,
    thumbnail: 'https://img.youtube.com/vi/6HLIFMyJxWA/maxresdefault.jpg',
  },
  {
    title: 'demo-reel',
    player: 'youtube',
    url: '2mtccBT0ajk',
    start: 0,
    thumbnail: 'https://img.youtube.com/vi/2mtccBT0ajk/maxresdefault.jpg',
  },
];

export const videosData = [
  {
    title: 'Hotel-California-Odissi',
    player: 'youtube',
    url: 'Fhp1pVrqOlE',
    start: 4,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/Fhp1pVrqOlE/maxresdefault.jpg',
  },
  {
    title: 'Neel-Digante-Folk',
    player: 'youtube',
    url: 'PjKssalnDxQ',
    start: 5,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/PjKssalnDxQ/maxresdefault.jpg',
  },
  {
    title: 'Prema-Prema',
    player: 'youtube',
    url: 'fplAPb4FEx0',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/fplAPb4FEx0/maxresdefault.jpg',
  },
  {
    title: 'Albela-Sajan-HipHop',
    player: 'youtube',
    url: 'zGYPqQDf9Iw',
    start: 4,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/zGYPqQDf9Iw/maxresdefault.jpg',
  },
  {
    title: 'Kathak-Senorita-Despacito',
    player: 'youtube',
    url: 'G_nSq-cVdGU',
    start: 4,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/G_nSq-cVdGU/maxresdefault.jpg',
  },
  {
    title: 'Swarabindu',
    player: 'youtube',
    url: 'ECuFmeDuo9k',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/ECuFmeDuo9k/maxresdefault.jpg',
  },
  {
    title: 'Thillana-2',
    player: 'youtube',
    url: 'XjouopoWpTQ',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/XjouopoWpTQ/hqdefault.jpg',
  },
  {
    title: 'Visweta-Aladdin',
    player: 'youtube',
    url: 'Pc1_dJzxf68',
    start: 12,
    Director: true,
    Editor: true,
    'Short-Films': true,
    thumbnail: 'https://img.youtube.com/vi/Pc1_dJzxf68/maxresdefault.jpg',
  },
  {
    title: 'Ek-do-teen',
    player: 'youtube',
    url: '6HLIFMyJxWA',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/6HLIFMyJxWA/maxresdefault.jpg',
  },
  {
    title: 'Sound-of-Silence-Manipuri',
    player: 'youtube',
    url: 'wDpCEtKKDqo',
    start: 4,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/wDpCEtKKDqo/maxresdefault.jpg',
  },
  {
    title: 'Rongila-Re-Mon-Folk',
    player: 'youtube',
    url: '5q1TaIoZqkM',
    start: 4,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/5q1TaIoZqkM/maxresdefault.jpg',
  },
  {
    title: 'Saa-boo-III',
    player: 'youtube',
    url: 'KlzRxpRlmeQ',
    start: 0,
    Director: true,
    Editor: true,
    'Short-Films': true,
    thumbnail: 'https://img.youtube.com/vi/KlzRxpRlmeQ/maxresdefault.jpg',
  },
  {
    title: 'Shivam',
    player: 'youtube',
    url: 'pnW0WqOx36U',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/pnW0WqOx36U/maxresdefault.jpg',
  },
  {
    title: 'Koova-2',
    player: 'youtube',
    url: 'LKnxcz9hjVw',
    start: 15,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/LKnxcz9hjVw/hqdefault.jpg',
  },
  {
    title: 'Ghoongarava',
    player: 'youtube',
    url: '4oVnO0cZ2UU',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/4oVnO0cZ2UU/maxresdefault.jpg',
  },
  {
    title: 'Kaapi-thillana',
    player: 'youtube',
    url: 'COe5FvtEkxg',
    start: 2,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/COe5FvtEkxg/maxresdefault.jpg',
  },
  {
    title: 'Light-projection-dance',
    player: 'youtube',
    url: 'ArkE9nQieIc',
    start: 4,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/ArkE9nQieIc/maxresdefault.jpg',
  },
  {
    title: '3D-Vittaai',
    player: 'youtube',
    url: 'vkGTNMXjsvg',
    start: 0,
    Director: true,
    Editor: true,
    'Short-Films': true,
    thumbnail: 'https://img.youtube.com/vi/vkGTNMXjsvg/maxresdefault.jpg',
  },
  {
    title: 'Mahanati',
    player: 'youtube',
    url: 'kXN2GR0jTrY',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/kXN2GR0jTrY/maxresdefault.jpg',
  },
  {
    title: 'Dance-promo',
    player: 'youtube',
    url: 'SnHKSVr-ioU',
    start: 0,
    Editor: true,
    'Dance-Videos': true,
    Performer: true,
    thumbnail: 'https://img.youtube.com/vi/SnHKSVr-ioU/maxresdefault.jpg',
  },
  {
    title: 'Kan-note-am',
    player: 'youtube',
    url: 'sRuogD2lj-U',
    start: 0,
    Director: true,
    Editor: true,
    'Short-Films': true,
    thumbnail: 'https://img.youtube.com/vi/sRuogD2lj-U/maxresdefault.jpg',
  },
  {
    title: 'Dance-constant',
    player: 'youtube',
    url: 'mu-jzfpd814',
    start: 0,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/mu-jzfpd814/maxresdefault.jpg',
  },
  {
    title: 'Nayantara-tribute',
    player: 'youtube',
    url: 'vFPyrjz-uZo',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/vFPyrjz-uZo/maxresdefault.jpg',
  },
  {
    title: 'Indre-kollum',
    player: 'youtube',
    url: 'hYxwpQDn2IU',
    start: 0,
    Performer: true,
    Editor: true,
    'Short-Films': true,
    thumbnail: 'https://img.youtube.com/vi/hYxwpQDn2IU/maxresdefault.jpg',
  },
  {
    title: 'Neeye-sol',
    player: 'youtube',
    url: 'rPN05DTv95o',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/rPN05DTv95o/maxresdefault.jpg',
  },
  {
    title: 'Crown-jathi-mix',
    player: 'youtube',
    url: '4UhTTB4z6qE',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/4UhTTB4z6qE/hqdefault.jpg',
  },
  {
    title: 'Zingaat-dance',
    player: 'youtube',
    url: 'Vwl-b6I_RBw',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/Vwl-b6I_RBw/maxresdefault.jpg',
  },
  {
    title: 'Karuvizhi-karuvi',
    player: 'youtube',
    url: 'u2HffXNnUiY',
    start: 0,
    Editor: true,
    'Short-Films': true,
    thumbnail: 'https://img.youtube.com/vi/u2HffXNnUiY/maxresdefault.jpg',
  },
  {
    title: 'Seemaraja-dance',
    player: 'youtube',
    url: 'MhVWfj3z69E',
    start: 0,
    Performer: true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/MhVWfj3z69E/maxresdefault.jpg',
  },
  {
    title: 'Believer-dance',
    player: 'youtube',
    url: 'wthTwi7U1mc',
    start: 52,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/wthTwi7U1mc/maxresdefault.jpg',
  },
  {
    title: 'Once-again-dance',
    player: 'youtube',
    url: '_pn4T2mZaYQ',
    start: 0,
    Performer: true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/_pn4T2mZaYQ/maxresdefault.jpg',
  },
  {
    title: 'Suzharchi',
    player: 'youtube',
    url: 'JopIo5rombc',
    start: 0,
    Editor: true,
    'Short-Films': true,
    thumbnail: 'https://img.youtube.com/vi/JopIo5rombc/maxresdefault.jpg',
  },
  {
    title: 'Shake-it-off-dance',
    player: 'youtube',
    url: 'ty9oKJnKm7w',
    start: 44,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/ty9oKJnKm7w/maxresdefault.jpg',
  },
  {
    title: 'Sanhiti-IPL-dance',
    player: 'youtube',
    url: '8LwT7-A18Ho',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/8LwT7-A18Ho/maxresdefault.jpg',
  },
  {
    title: 'Mungda-dance',
    player: 'youtube',
    url: 'hv7x6lcJjLE',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/hv7x6lcJjLE/maxresdefault.jpg',
  },
  {
    title: 'Velai-evanidam',
    player: 'youtube',
    url: 'q0aWIQ-9bVs',
    start: 0,
    Editor: true,
    'Short-Films': true,
    thumbnail: 'https://img.youtube.com/vi/q0aWIQ-9bVs/hqdefault.jpg',
  },
  {
    title: 'Nilave-mugam-kaatu',
    player: 'youtube',
    url: 'acIvgCl8pys',
    start: 0,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/acIvgCl8pys/maxresdefault.jpg',
  },
  {
    title: 'Rowdy-baby-dance',
    player: 'youtube',
    url: 'VX84P8qGY1Q',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/VX84P8qGY1Q/hqdefault.jpg',
  },
  {
    title: 'Break-the-rules-dance',
    player: 'youtube',
    url: '0QEmozeynSo',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/0QEmozeynSo/hqdefault.jpg',
  },
  {
    title: 'Null-hypothesis',
    player: 'youtube',
    url: 'nAlreN8y5rI',
    start: 0,
    Editor: true,
    'Short-Films': true,
    thumbnail: 'https://img.youtube.com/vi/nAlreN8y5rI/maxresdefault.jpg',
  },
  {
    title: 'Cant-stop-the-feeling',
    player: 'youtube',
    url: '0TUfbNHg9ZE',
    start: 0,
    Editor: true,
    'Dance-Videos': true,
    'D.o.P': true,
    thumbnail: 'https://img.youtube.com/vi/0TUfbNHg9ZE/maxresdefault.jpg',
  },
  {
    title: 'Dhaari-choodu-dance',
    player: 'youtube',
    url: 'EyBYPlsqz4w',
    start: 0,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/EyBYPlsqz4w/maxresdefault.jpg',
  },
  {
    title: 'Pilichinda-dance',
    player: 'youtube',
    url: 'BlUBzEocQe8',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/BlUBzEocQe8/maxresdefault.jpg',
  },
  {
    title: 'Nallavela-suttutaanunga',
    player: 'youtube',
    url: '5Ft3hdqHNpg',
    start: 0,
    Editor: true,
    'Short-Films': true,
    thumbnail: 'https://img.youtube.com/vi/5Ft3hdqHNpg/maxresdefault.jpg',
  },
  {
    title: 'game-trailer',
    player: 'youtube',
    url: 'aN0ZXV8ux58',
    start: 0,
    Director: true,
    Editor: true,
    'Short-Films': true,
    thumbnail: 'https://img.youtube.com/vi/aN0ZXV8ux58/maxresdefault.jpg',
  },
  {
    title: 'Dont-stop-dance',
    player: 'youtube',
    url: 'aj9-E4-mTA4',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/aj9-E4-mTA4/maxresdefault.jpg',
  },
  {
    title: 'Say-something-dance',
    player: 'youtube',
    url: 'DAy02w2v2bo',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/DAy02w2v2bo/maxresdefault.jpg',
  },
  {
    title: 'Akh-Lad-Jaave-dance',
    player: 'youtube',
    url: 'HpdLCWkDYfw',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/HpdLCWkDYfw/maxresdefault.jpg',
  },
  {
    title: 'Maari-dance',
    player: 'youtube',
    url: 'zzaFIViZpc0',
    start: 0,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/zzaFIViZpc0/maxresdefault.jpg',
  },
  {
    title: 'It-wasnt-me-dance',
    player: 'youtube',
    url: 'p6wQsRHdG-A',
    start: 0,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/p6wQsRHdG-A/maxresdefault.jpg',
  },
  {
    title: 'Milegi-dance',
    player: 'youtube',
    url: 'KXbqY-UYCH8',
    start: 0,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/KXbqY-UYCH8/maxresdefault.jpg',
  },
  {
    title: 'Mama-douser-dance',
    player: 'youtube',
    url: '6-6OxsKPWAE',
    start: 685,
    Performer: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/6-6OxsKPWAE/maxresdefault.jpg',
  },
  {
    title: 'Theeratha-dance',
    player: 'youtube',
    url: 'jX6ZnlVwo_I',
    start: 1050,
    Performer: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/jX6ZnlVwo_I/hqdefault.jpg',
  },
  {
    title: 'Kasu-mela-dance',
    player: 'youtube',
    url: 'zTor5l7h3u8',
    start: 4175,
    Performer: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/zTor5l7h3u8/maxresdefault.jpg',
  },
  {
    title: 'Editing-classical-dance',
    player: 'youtube',
    url: 'gFR14gPn1dQ',
    start: 82,
    Director: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/gFR14gPn1dQ/maxresdefault.jpg',
  },
  {
    title: 'Lighting-contemporary-dance',
    player: 'youtube',
    url: 'e7s6dtEfU4E',
    start: 45,
    Director: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/e7s6dtEfU4E/hqdefault.jpg',
  },
  {
    title: 'Top-down-camera-dance',
    player: 'youtube',
    url: 'CNDshA69NH4',
    start: 63,
    Director: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/CNDshA69NH4/maxresdefault.jpg',
  },
  {
    title: 'Soara-music-video',
    player: 'youtube',
    url: 'yWRHvXKukQY',
    start: 4,
    'D.o.P': true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/yWRHvXKukQY/maxresdefault.jpg',
  },
  {
    title: 'Mi-gente-bharatnatyam',
    player: 'youtube',
    url: 'nU26HNruRSc',
    start: 4,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/nU26HNruRSc/maxresdefault.jpg',
  },
  {
    title: 'Bengali-finale',
    player: 'youtube',
    url: 'xaG2T03aE0k',
    start: 4,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/xaG2T03aE0k/maxresdefault.jpg',
  },
  {
    title: 'Jab-koi-baat-bollyfusion',
    player: 'youtube',
    url: '3ZNWNFL4omA',
    start: 4,
    'D.o.P': true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/3ZNWNFL4omA/maxresdefault.jpg',
  },
  {
    title: 'Pathala-pathala',
    player: 'youtube',
    url: 'H6GC0mm7G28',
    start: 0,
    Performer: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/H6GC0mm7G28/hqdefault.jpg',
  },
  {
    title: 'etc-music-video',
    player: 'youtube',
    url: 'VORhnpUUtig',
    start: 10,
    Director: true,
    Editor: true,
    'Dance-Videos': true,
    thumbnail: 'https://img.youtube.com/vi/VORhnpUUtig/maxresdefault.jpg',
  },
  {
    title: 'Twitmania',
    player: 'youtube',
    url: 'OyNTsqI22cI',
    start: 0,
    Editor: true,
    thumbnail: 'https://img.youtube.com/vi/OyNTsqI22cI/hqdefault.jpg',
  },
];
