export const demo = {
  title: 'demo-reel',
  player: 'youtube',
  url: '2mtccBT0ajk',
  start: 0,
};

const videos = [
  {
    title: 'Thillana-2',
    player: 'youtube',
    url: 'XjouopoWpTQ',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Visweta-Aladdin',
    player: 'youtube',
    url: 'Pc1_dJzxf68',
    start: 12,
    Director: true,
    Editor: true,
    ShortFilms: true,
  },
  {
    title: 'Ek-do-teen',
    player: 'youtube',
    url: '6HLIFMyJxWA',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Saa-boo-III',
    player: 'youtube',
    url: 'KlzRxpRlmeQ',
    start: 0,
    Director: true,
    Editor: true,
    ShortFilms: true,
  },
  {
    title: 'Shivam',
    player: 'youtube',
    url: 'pnW0WqOx36U',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Koova-2',
    player: 'youtube',
    url: 'LKnxcz9hjVw',
    start: 15,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: '3D-Vittaai',
    player: 'youtube',
    url: 'vkGTNMXjsvg',
    start: 0,
    Director: true,
    Editor: true,
    ShortFilms: true,
  },
  {
    title: 'Mahanati',
    player: 'youtube',
    url: 'kXN2GR0jTrY',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Dance-promo',
    player: 'youtube',
    url: 'SnHKSVr-ioU',
    start: 0,
    Editor: true,
    DanceVideos: true,
    Performer: true,
  },
  {
    title: 'Kan-note-am',
    player: 'youtube',
    url: 'sRuogD2lj-U',
    start: 0,
    Director: true,
    Editor: true,
    ShortFilms: true,
  },
  {
    title: 'Dance-constant',
    player: 'youtube',
    url: 'mu-jzfpd814',
    start: 0,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Nayantara-tribute',
    player: 'youtube',
    url: 'vFPyrjz-uZo',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Indre-kollum',
    player: 'youtube',
    url: 'hYxwpQDn2IU',
    start: 0,
    Performer: true,
    Editor: true,
    ShortFilms: true,
  },
  {
    title: 'Neeye-sol',
    player: 'youtube',
    url: 'rPN05DTv95o',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Crown-jathi-mix',
    player: 'youtube',
    url: '4UhTTB4z6qE',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Zingaat-dance',
    player: 'youtube',
    url: 'Vwl-b6I_RBw',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Karuvizhi-karuvi',
    player: 'youtube',
    url: 'u2HffXNnUiY',
    start: 0,
    Editor: true,
    ShortFilms: true,
  },
  {
    title: 'Seemaraja-dance',
    player: 'youtube',
    url: 'MhVWfj3z69E',
    start: 0,
    Performer: true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Believer-dance',
    player: 'youtube',
    url: 'wthTwi7U1mc',
    start: 52,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Once-again-dance',
    player: 'youtube',
    url: '_pn4T2mZaYQ',
    start: 0,
    Performer: true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Suzharchi',
    player: 'youtube',
    url: 'JopIo5rombc',
    start: 0,
    Editor: true,
    ShortFilms: true,
  },
  {
    title: 'Shake-it-off-dance',
    player: 'youtube',
    url: 'ty9oKJnKm7w',
    start: 44,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Sanhiti-IPL-dance',
    player: 'youtube',
    url: '8LwT7-A18Ho',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Mungda-dance',
    player: 'youtube',
    url: 'hv7x6lcJjLE',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Velai-evanidam',
    player: 'youtube',
    url: 'q0aWIQ-9bVs',
    start: 0,
    Editor: true,
    ShortFilms: true,
  },
  {
    title: 'Nilave-mugam-kaatu',
    player: 'youtube',
    url: 'acIvgCl8pys',
    start: 0,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Rowdy-baby-dance',
    player: 'youtube',
    url: 'VX84P8qGY1Q',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Break-the-rules-dance',
    player: 'youtube',
    url: '0QEmozeynSo',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Null-hypothesis',
    player: 'youtube',
    url: 'nAlreN8y5rI',
    start: 0,
    Editor: true,
    ShortFilms: true,
  },
  {
    title: 'Cant-stop-the-feeling',
    player: 'youtube',
    url: '0TUfbNHg9ZE',
    start: 0,
    Editor: true,
    DanceVideos: true,
    'D.o.P': true,
  },
  {
    title: 'Dhaari-choodu-dance',
    player: 'youtube',
    url: 'EyBYPlsqz4w',
    start: 0,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Pilichinda-dance',
    player: 'youtube',
    url: 'BlUBzEocQe8',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Nallavela-suttutaanunga',
    player: 'youtube',
    url: '5Ft3hdqHNpg',
    start: 0,
    Editor: true,
    ShortFilms: true,
  },
  {
    title: 'Dont-stop-dance',
    player: 'youtube',
    url: 'aj9-E4-mTA4',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Say-something-dance',
    player: 'youtube',
    url: 'DAy02w2v2bo',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Akh-Lad-Jaave-dance',
    player: 'youtube',
    url: 'HpdLCWkDYfw',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Twitmania',
    player: 'youtube',
    url: 'OyNTsqI22cI',
    start: 0,
    Editor: true,
  },
  {
    title: 'Maari-dance',
    player: 'youtube',
    url: 'zzaFIViZpc0',
    start: 0,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'It-wasnt-me-dance',
    player: 'youtube',
    url: 'p6wQsRHdG-A',
    start: 0,
    'D.o.P': true,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Milegi-dance',
    player: 'youtube',
    url: 'KXbqY-UYCH8',
    start: 0,
    Editor: true,
    DanceVideos: true,
  },
  {
    title: 'Mama-douser-dance',
    player: 'youtube',
    url: '6-6OxsKPWAE',
    start: 685,
    Performer: true,
    DanceVideos: true,
  },
  {
    title: 'Theeratha-dance',
    player: 'youtube',
    url: 'jX6ZnlVwo_I',
    start: 1050,
    Performer: true,
    DanceVideos: true,
  },
  {
    title: 'Kasu-mela-dance',
    player: 'youtube',
    url: 'zTor5l7h3u8',
    start: 4175,
    Performer: true,
    DanceVideos: true,
  },
  {
    title: 'Editing-classical-dance',
    player: 'youtube',
    url: 'gFR14gPn1dQ',
    start: 82,
    Director: true,
    DanceVideos: true,
  },
  {
    title: 'Lighting-contemporary-dance',
    player: 'youtube',
    url: 'e7s6dtEfU4E',
    start: 45,
    Director: true,
    DanceVideos: true,
  },
  {
    title: 'Top-down-camera-dance',
    player: 'youtube',
    url: 'CNDshA69NH4',
    start: 63,
    Director: true,
    DanceVideos: true,
  },
];

export default videos;
